<?php
@header('Content-Type: text/html; charset=utf-8');
require_once "Clube.php";
require_once 'Bitaites.php'; 
require_once 'Video.php'; 
require_once "Competicao.php";
require_once "DAO.php";
require_once "Fonte.php";
require_once "Funcao.php";
require_once "Integrante.php";
require_once "Integrante_imagem.php"; 
require_once "Lexico.php";
require_once "Local.php";
require_once "Noticia_locais.php";
require_once "Noticia.php";
require_once "Clubes_Lexico.php"; 
require_once "Noticia_Has_Clube.php"; 
require_once "Noticia_Has_Integrante.php"; 
require_once "Integrantes_Lexico.php";
require_once "Comentario.php";
require_once "Noticia_Data.php"; 
require_once "Clube_Imagem.php"; 
require_once "Nr_noticia_data.php";
require_once "Nr_noticia_local_clube.php"; 
require_once "Nr_noticia_integrante.php"; 
require_once "Noticia_x_clube.php"; 
require_once "Noticia_data_clube.php";
require_once "Nr_noticia_local.php";
//require_once "lib/Util.php";
?>